//tebak fungsinya apa
export const kemenbiroList = [
	{
		id: "presiden",
		title: "Presiden",
		tipe: "Pengurus Inti",
		jabatan: ["Presiden BEM"],
		bph: ["M. Verrel Radiman"],
		tupoksi:
			"Pengambil kebijakan tertinggi serta bertanggung jawab akan segala kegiatan dan aktivitas BEM FILKOM UB yang menjalankan fungsi kepemimpinan secara umum.",
	},
	{
		id: "wakilpresiden",
		title: "Wakil Presiden",
		tipe: "Pengurus Inti",
		jabatan: ["Wakil Presiden BEM"],
		bph: ["M. Jordan Farrell"],
		tupoksi:
			"Mendampingi dan membantu Presiden BEM dalam menjalankan tugasnya serta menggantikan fungsi dan peran Presiden BEM jika berhalangan. Wakil Presiden BEM juga bertanggung jawab akan segala kegiatan dan aktivitas BEM FILKOM UB bersama Presiden BEM.",
	},
	{
		id: "sekpim",
		title: "Sekretaris Pimpinan",
		tipe: "Pengurus Inti",
		jabatan: ["Sekretaris Pimpinan"],
		bph: ["Jeowandha Ria Wiyani"],
		tupoksi:
			"Bertanggung jawab dalam mengkoordinasikan agenda dari Presiden dan Wakil Presiden BEM FILKOM UB. Sekretaris Pimpinan juga bertanggung jawab dalam hal administratif berhubungan dengan program kerja BEM FILKOM UB untuk pelaporan kepada Presiden dan Wakil Presiden BEM maupun publik.",
	},
	{
		id: "supervisor",
		title: "Supervisor",
		tipe: "Pengurus Inti",
		jabatan: ["Supervisor", "Supervisor"],
		bph: ["Ahmad Farhan", "Fawwaz Roja M."],
		tupoksi:
			"Melakukan pengawasan terhadap kementerian dan biro BEM FILKOM UB terkait dengan Goals Kementerian dan Ketercapaian program kerja. Selain itu, supervisor juga melakukan koordinasi dan sinkronisasi kementerian dan biro BEM FILKOM UB.",
	},
	{
		id: "psdi",
		title: "Pengembangan Sumber Daya Internal",
		tipe: "Pengurus Inti",
		jabatan: [
			"Koordinator",
			"Wakil Koodinator",
			"Anggota",
			"Anggota",
			"Anggota",
			"Anggota",
			"Anggota",
			"Anggota",
		],
		bph: [
			"Yusuf Putra A.",
			"Nisa Usrifatul J.",
			"Tiffany Rizka F.",
			"M. Lukman Wibowo",
			"M. Irfan Nugraha",
			"Nabilah Syarifa Z.",
			"Christie Viviah C.",
			"Onky Soerya N.U.",
		],
		tupoksi:
			"Melakukan fungsi monitoring dan evaluasi terhadap kinerja dan personality sumber daya manusia BEM FILKOM UB. Selain itu PSDI juga bertugas sebagai inisiator dari peningkatan kapabilitas (upgrading) dan peningkatan solidaritas (bonding) seluruh sumber daya manusia BEM FILKOM UB berdasarkan hasil monitoring dan evaluasi.",
		proker: [
			"TRAINING ORGANIZATION",
			"UPGRADING",
			"BONDING",
			"MONITORING AND EVALUATION"
		]
	},
	{
		id: "psdm",
		title: "Pengembangan Sumber Daya Manusia",
		tipe: "Kementerian",
		jabatan: ["Menteri", "Dirjen Kaderisasi", "Dirjen P2M"],
		bph: ["Rangga Baghas N.", "Fadhil Arif M.", "M. Guntur Dermawan"],
		tupoksi:
			"Bertanggung jawab dalam pembentukan karakter dan Pengembangan Potensi Sumber daya manusia Mahasiswa FILKOM untuk menciptakan karakter dan kemampuan mahasiswa yang ideal dalam kehidupan kampus hingga pasca kampus.",
		proker: [
			"PK2MABA & STARTUP ACADEMY",
			"LOKAKARYA KADERISASI 2.0",
			"STAFF MUDA BEM FILKOM",
			"INAUGURASI FILKOM",
			"LKMM-TM",
			"LEADERS OF TOMORROW",
			"FILAFEST",
			"FILKOM MANNER TIPS: JILID III",
		],
		staff: [
			"Andriko Fajar Prakoso",
			"Dwinanda Romolo",
			"Hanifa Putri Rahima",
			"Huriyah Anisah N. Humairoh",
			"Khadija Rahmanisa P.P.",
			"Muhammad Makbul Zaid",
			"Raudhotul Jannah",
			"Zeta Zidanne Bihesa",
		],
	},
	{
		id: "perhub",
		title: "Perhubungan",
		tipe: "Kementerian",
		jabatan: ["Menteri", "Dirjen Dalam Negeri", "Dirjen Luar Negeri"],
		bph: ["Dito William H.", "Adi Wiyanto", "M. Hardian Ghaffari"],
		tupoksi:
			"Bertanggung jawab dalam menjalin hubungan dan koordinasi dengan lembaga mahasiswa FILKOM UB dan pihak Eksternal BEM FILKOM UB, " +
			"menjalin koordinasi, konsolidasi dan monitoring terhadap Lembaga Kemahasiswaan FILKOM UB, " +
			"menjalin Hubungan dan Koordinasi antara pihak Eksternal FILKOM UB dan BEM FILKOM UB.",
		proker: [
			"GRAND LAUNCHING LEMBAGA DAN KOMUNITAS FILKOM",
			"SAMBANG LEMBAGA",
			"FORUM ALUMNI",
			"LEMBAGA D-DAY",
			"LEMBAGA AWARDS",
			"STUDI BANDING",
			"MONITORING DAN TURUN LAPANG",
			"FILKOM GOES TO SCHOOL (FGTS)",
			"AUDIT CITRA INTERNAL",
			"AUDIT CITRA EKSTERNAL",
		],
		staff: [
			"Abi Aryaza",
			"Adhistia Salsabila Putri",
			"Aldo Friska Darma Putra",
			"Alizza Iman Raddin",
			"Dhimas Arfian Lazzuardhy",
			"Muhammad Daffa Syah D.",
			"Rifki Karim Ramadhan",
			"Sofi Shahira Khairunnisa",
			"Yesaya Sergio Vito P.",
		],
	},
	{
		id: "k2p",
		title: "Keilmuan Karir Prestatif",
		tipe: "Kementerian",
		jabatan: ["Menteri", "Wakil Menteri"],
		bph: ["Vearen Dika S.", "M Irfan Yusuf W."],
		tupoksi:
			"Bertanggung jawab dalam Mengakomodasi dan Mengapresiasi prestasi mahasiswa Filkom di bidang Ilmu Komputer autaupun secara umum. K2P juga bertujuan untuk membantu dan menunjang minat Mahasiswa FILKOM di ranah Karir Ilmu Komputer.",
		proker: [
			"HOLOGY 3.0 (House of Technology)",
			"IT TALK (Inspiration Technology Talk)",
			"MAWAPRES FILKOM",
			"KANAL PRESTASI",
			"FILKOM PINTAR",
			"CAREER HACK",
			"CAREER INFO",
		],
		staff: [
			"Dhania Tami Wijaya",
			"Hafizh Daffa Septianto",
			"M. Nugraha Delta R.",
			"Sinta Dwi Ayu Kumala",
			"Syahida Usama Firdaus",
		],
	},
	{
		id: "kastrat",
		title: "Kajian dan Aksi Strategis",
		tipe: "Kementerian",
		jabatan: ["Menteri", "Wakil Menteri"],
		bph: ["Araffathoni Rizqi", "Rafi Arya Siregar"],
		tupoksi:
			"Bertanggungjawab dalam mengawal isu-isu strategis dengan melakukan pencerdasan, propaganda, dan pengkajian terhadap isu di ranah universitas, regional, nasional, maupun internasional.",
		proker: [
			"FILKOM BERBANGSA",
			"KASUS APA",
			"RAPOR MERAH",
			"JAVA",
			"PANSOS",
		],
		staff: [
			"Farid Syauqi Nirwan",
			"Irfan Jesia Abyakta",
			"Ivanna Adista Sihombing",
			"Muhammad Fadhel Haidar",
			"Nur Alif Firmansyah",
		],
	},
	{
		id: "sosling",
		title: "Sosial dan Lingkungan",
		tipe: "Kementerian",
		jabatan: ["Menteri", "Dirjen Pengmas", "Dirjen LH"],
		bph: ["Azzahra Princessa S.W.", "Dimi Karillah Putra", "Afifah Khairunnisa"],
		tupoksi:
			"Bertanggung jawab di bidang pelayanan masyarakat serta lingkungan hidup dengan melakukan pengembangan melalui program dan aksi nyata yang dapat dilakukan mulai dari agen pencerdasan bangsa di bidang pendidikan, peduli lingkungan hidup bermasyarakat, bantuan sosial yang aktif dan pengabdian kepada masyarakat, serta menciptakan kepedulian sosial terhadap masyarakat." +
			"Bertanggung jawab di bidang pelayanan masyarakat dengan melakukan pengabdian dalam bentuk aksi nyata dan pencerdasan sebagai upaya menciptakan kesejahteraan masyarakat." +
			"Bertanggung jawab di bidang Lingkungan Hidup dengan menjaga kesehatan lingkungan, aksi nyata dan pencerdasan, serta mendorong kegiatan pelestarian lingkungan yang dapat memberikan kesejahteraan bagi masyarakat.",
		proker: [
			"FILKOM ABDIMASA",
			"SOCIAL ISSUE ON FOCUS",
			"FILKOM RAMADHAN",
			"FILKOM PEDULI",
			"#TREEFORLIFE",
			"SOCIAL INSIGHT",
			"FILKOM SIGN",
			"ACT FOR ENVIRONMENTAL ISSUES",
			"FILKOM BERSIH",
			"E-UPDATE",
		],
		staff: [
			"Dandy Ramadhany",
			"Desi Rosda Arum Sari",
			"Ghina Zahirah",
			"Hilmy Saeful Fatah",
			"La Ode Adriyan Hazmar",
			"Lenny Raufi Syafitri",
			"Stephen Pholim",
			"Yolanda Saputri",
		],
	},
	{
		id: "advokesma",
		title: "Advokasi dan Kesejahteraan Mahasiswa",
		tipe: "Kementerian",
		jabatan: ["Menteri", "Wakil Menteri"],
		bph: ["Aruf Rachman H.", "Carly Vyoletta S."],
		tupoksi:
			"Bertanggungjawab dalam melakukan kegiatan advokasi terhadap permasalahan mahasiswa kepada pihak terkait sebagai bentuk perjuangan aspirasi mahasiswa. Selain itu Advokesma juga bertugas utnuk menghimpun permasalahan dan menyampaikan informasi terkait kesejahteraan mahasiswa." +
			"Mengkaji kebijakan kampus FILKOM UB dan melakukan fungsi advokasi kepada pihak terkait akan suatu permasalahan dengan tujuan memperjuangkana aspirasi mahasiswa." +
			"Menghimpun permasalahan mahasiswa secara komprehensif dan menyampiakan informasi-informasi yang terkait dengan kondisi kesejahteraan mahasiswa.",
		proker: [
			"DEWA NGODING",
			"EXPO BEASISWA",
			"BEASISWA SOLIDARITAS FILKOM",
			"SUARAKAN ASA",
			"KABAR DAN POSKO ADVOKESMA",
			"REPORT & PROGRESS ADVOKESMA",
			"ADVOKASI TURUN TANGAN",
			"CRISIS CENTER UKT",
			"BEASISWA CARE CENTER",
		],
		staff: [
			"Andhika Rizky Fariz",
			"Ahmad Kholish Fauzan Shobiry",
			"Graita Sukma F.T.A.",
			"Ihza Aulya Nanda",
			"Kautsarratu Athaya Z.",
			"Mochammad Zava Abbiyansyah",
			"Nadya Nur Fadhila ",
			"Sarah Uli Octavia",
		],
	},
	{
		id: "bismit",
		title: "Bisnis dan Kemitraan",
		tipe: "Kebiroan",
		jabatan: ["Kabiro", "Wakabiro"],
		bph: ["Arbi Ramadhan A.A.", "Rahadian Fitra S."],
		tupoksi:
			"Bertanggungjawab dalam penghimunan sumber dana secara mandiri dari usaha bisnis kreatif atau menjalin kemitraan dengan perusahaan dan/atau korporasi guna menunjang finansial internal BEM FILKOM UB",
		proker: [
			"BEM BUSINESS PROGRAM",
			"PARTNERSHIP",
			"FINANCIAL PROJECT",
			"BUSINESS WORKSHOP",
		],
		staff: [
			"Alfina Ayu Aulia",
			"Ferrinda Aprilia K.S.H.",
			"Hanifatul Izza",
			"Muhammad Ifa Amrillah",
			"Wisnumurti",
		],
	},
	{
		id: "pit",
		title: "Pengembangan Informasi dan Teknologi",
		tipe: "Kebiroan",
		jabatan: ["Kabiro", "Wakabiro"],
		bph: ["Puras Handharmahua", "Nourman Hajar"],
		tupoksi:
			"Bertanggungjawab dalam pengimplementasian teknologi informasi yang ditujukan sebagai penunjang penyebaran informasi, media branding dan supporting kegiatan program kerja BEM FILKOM.",
		proker: [
			"UPDATE WEBSITE BEM",
			"WEB EVENT REQUEST",
			"BEM APPS",
			"FILKOMPEDIA",
			"WORKSHOP INTERNAL",
		],
		staff: [
			"Muhammad Fajar Alfath",
			"Munirotul Millah",
			"Safir Rahmahuda Machsun",
		],
	},
	{
		id: "adkeu",
		title: "Administrasi Kesekretariatan dan Keuangan",
		tipe: "Kebiroan",
		jabatan: ["Kabiro", "Wakabiro"],
		bph: ["Civica Mohaemin D.", "Shahnaz Maulidini A."],
		tupoksi:
			"Bertanggungjawab dalam menunjang kegiatan BEM FILKOM dalam bidang keseketariatan, pengelolaan inventaris dan pengelolaan keuangan." +
			"Mengelola keuangan internal BEM FILKOM UB dalam bentuk pembukuan dan juga melakukan pengecekan dana yang diajukan oleh Lembaga di FILKOM ataupun pengajuan lomba di lingkup FILKOM UB." +
			"Bertugas dalam menunjang BEM FILKOM UB dalam hal hal yang berhubungan dengan keseketariatan (Persuratan, Proposal, dan LPJ), administrasi dan pengelolaan inventaris BEM FILKOM UB. Selain itu Adkest juga melakukan pengecekan surat-surat, Proposal dan LPJ yang diajukan oleh Lembaga di Filkom ataupun pengajuan lomba di lingkup FILKOM UB.",
		proker: [
			"PEGELOLAAN DAN PENGARSIPAN SURAT, PROPOSAL, DAN LPJ",
			"INVENTARISASI DAN RUANG SEKRETARIAT BEM FILKOM",
			"PIKET DAN JUMAT BERSIH",
			"INTEGRASI PEMINJAMAN",
			"LAPORAN KEUANGAN INTERNAL",
			"LAPORAN KEUANGAN EKSTERNAL",
		],
		staff: [
			"Anatasia Griselda Ferina B.",
			"Annisa Sukmawati",
			"Devina Dwi pratiwi",
			"Dyah Ayu Wulandari",
			"Yushinta Prassanty A.",
		],
	},
	{
		id: "medinkraf",
		title: "Media Informasi dan Kreatif",
		tipe: "Kebiroan",
		jabatan: ["Kabiro", "Kabag Medkraf", "Kabag Medinfo"],
		bph: ["Rifki Akbar S.", "Ediashta Revindra A.", "Chusna Farida I."],
		tupoksi:
			"Bertanggungjawab dalam optimalisasi sosial media BEM FILKOM UB dengan pembuatan dan penyebaran informasi secara kreatif terhadap seluruh aktivitas dan kegiatan BEM FILKOM UB melalui media sosial." +
			"\nMenerjemahkan informasi kedalam Konten Kreatif berupa video dan atau gambar sebagai bentuk penyebaran informasi yang kreatif dan inovatif mengenai kegiatan BEM FILKOM UB." +
			"\nMengelola Media Sosial BEM FILKOM dan melaksanakan penyebaran informasi yang akurat dan informatif mengenai kegiatan dan akrivitas BEM FILKOM UB serta bertugas dalam pembuatan redaksional  dari setiap informasi yang akan disebarluaskan.",
		proker: [
			"LIVE REPORT KEGIATAN",
			"SOCIAL MEDIA MAINTENANCE",
			"MONTHLY TRIVIA CONTENT",
			"REKAM JEJAK",
			"C0MMITTEE PROFILE",
			"COMPANY PROFILE",
			"HUMAS & POSTER PARTNER",
			"JOWOAN YUK REK!",
			"GRAND LAUNCHING BEM FILKOM 2020",
		],
		staff: [
			"Jasmine Pratiwi Putri P.",
			"Maria Imaculata Astrid W.",
			"Muhammad Ibrahim Kumail",
			"Muhammad Magistra S.",
			"Muhammad Rizky Rais",
			"Muhammad Yusuf Ahmadi",
			"Rafeilia Safa Nurul Izza",
			"Randy Christian Saputra",
		],
	},
];
  